// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: APS_Base_4M

#ifndef _APS_BASE_4M_UI_H
#define _APS_BASE_4M_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * HELP1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HELP2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HELP3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HELP4_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_firefighter_gray_full_png);    // assets/firefighter gray_full.png
LV_IMG_DECLARE(ui_img_firefighter_red_full_png);    // assets/firefighter red_full.png
LV_IMG_DECLARE(ui_img_firefighter_yell_full_png);    // assets/firefighter yell_full.png
LV_IMG_DECLARE(ui_img_firefighter_green_full_png);    // assets/firefighter green_full.png
LV_IMG_DECLARE(ui_img_temperature_30_png);    // assets/temperature 30.png

// FONTS
LV_FONT_DECLARE(ui_font_Font60segment);
LV_FONT_DECLARE(ui_font_FontHelp50);
LV_FONT_DECLARE(ui_font_FontsWars50);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
