// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: APS_Base_4M

#include "ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_Titulo_Touch_Fire;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Gray1;
lv_obj_t * ui_Red1;
lv_obj_t * ui_Yellou1;
lv_obj_t * ui_Green1;
lv_obj_t * ui_HELP1;
lv_obj_t * ui_ImgTemp1;
lv_obj_t * ui_Temp1Back;
lv_obj_t * ui_Temp1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Gray2;
lv_obj_t * ui_ImgTemp2;
lv_obj_t * ui_Green2;
lv_obj_t * ui_Yellou2;
lv_obj_t * ui_Red2;
lv_obj_t * ui_Temp2Back;
lv_obj_t * ui_Temp2;
lv_obj_t * ui_HELP2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Temp3Back;
lv_obj_t * ui_ImgTemp3;
lv_obj_t * ui_Red3;
lv_obj_t * ui_Gray3;
lv_obj_t * ui_Yellou3;
lv_obj_t * ui_Temp3;
lv_obj_t * ui_HELP3;
lv_obj_t * ui_Green3;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Red4;
lv_obj_t * ui_Green4;
lv_obj_t * ui_Gray4;
lv_obj_t * ui_Yellou4;
lv_obj_t * ui_ImgTemp4;
lv_obj_t * ui_Temp4Back;
lv_obj_t * ui_Temp4;
lv_obj_t * ui_HELP4;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Titulo_Touch_Fire = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Titulo_Touch_Fire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Titulo_Touch_Fire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Titulo_Touch_Fire, -2);
    lv_obj_set_y(ui_Titulo_Touch_Fire, -195);
    lv_obj_set_align(ui_Titulo_Touch_Fire, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Titulo_Touch_Fire, "TouchFire   Station ");
    lv_obj_set_style_text_font(ui_Titulo_Touch_Fire, &ui_font_FontsWars50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 180);
    lv_obj_set_height(ui_Container1, 390);
    lv_obj_set_x(ui_Container1, -290);
    lv_obj_set_y(ui_Container1, 27);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gray1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Gray1, &ui_img_firefighter_gray_full_png);
    lv_obj_set_width(ui_Gray1, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_Gray1, LV_SIZE_CONTENT);    /// 259
    lv_obj_set_x(ui_Gray1, 0);
    lv_obj_set_y(ui_Gray1, -20);
    lv_obj_set_align(ui_Gray1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gray1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gray1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Gray1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Red1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Red1, &ui_img_firefighter_red_full_png);
    lv_obj_set_width(ui_Red1, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Red1, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_x(ui_Red1, 0);
    lv_obj_set_y(ui_Red1, -20);
    lv_obj_set_align(ui_Red1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Red1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Red1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Red1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Yellou1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Yellou1, &ui_img_firefighter_yell_full_png);
    lv_obj_set_width(ui_Yellou1, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_Yellou1, LV_SIZE_CONTENT);    /// 263
    lv_obj_set_x(ui_Yellou1, 0);
    lv_obj_set_y(ui_Yellou1, -20);
    lv_obj_set_align(ui_Yellou1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Yellou1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Yellou1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Yellou1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Green1, &ui_img_firefighter_green_full_png);
    lv_obj_set_width(ui_Green1, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_Green1, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_x(ui_Green1, 0);
    lv_obj_set_y(ui_Green1, -20);
    lv_obj_set_align(ui_Green1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Green1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Green1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Green1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HELP1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_HELP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HELP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HELP1, 3);
    lv_obj_set_y(ui_HELP1, 152);
    lv_obj_set_align(ui_HELP1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HELP1, "HELP");
  //  lv_obj_add_flag(ui_HELP1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_HELP1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HELP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HELP1, &ui_font_FontHelp50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HELP1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTemp1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_ImgTemp1, &ui_img_temperature_30_png);
    lv_obj_set_width(ui_ImgTemp1, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_ImgTemp1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgTemp1, -62);
    lv_obj_set_y(ui_ImgTemp1, 158);
    lv_obj_set_align(ui_ImgTemp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTemp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTemp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImgTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp1Back = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Temp1Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp1Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp1Back, 14);
    lv_obj_set_y(ui_Temp1Back, 160);
    lv_obj_set_align(ui_Temp1Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp1Back, "000");
    lv_obj_set_style_text_color(ui_Temp1Back, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp1Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp1Back, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp1Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp1, 22);
    lv_obj_set_y(ui_Temp1, 160);
    lv_obj_set_align(ui_Temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp1, "789");
    lv_obj_set_style_text_font(ui_Temp1, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 180);
    lv_obj_set_height(ui_Container2, 390);
    lv_obj_set_x(ui_Container2, -95);
    lv_obj_set_y(ui_Container2, 25);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gray2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Gray2, &ui_img_firefighter_gray_full_png);
    lv_obj_set_width(ui_Gray2, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_Gray2, LV_SIZE_CONTENT);    /// 259
    lv_obj_set_x(ui_Gray2, 0);
    lv_obj_set_y(ui_Gray2, -20);
    lv_obj_set_align(ui_Gray2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gray2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gray2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Gray2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTemp2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_ImgTemp2, &ui_img_temperature_30_png);
    lv_obj_set_width(ui_ImgTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgTemp2, -64);
    lv_obj_set_y(ui_ImgTemp2, 157);
    lv_obj_set_align(ui_ImgTemp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTemp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTemp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImgTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Green2, &ui_img_firefighter_green_full_png);
    lv_obj_set_width(ui_Green2, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_Green2, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_x(ui_Green2, 0);
    lv_obj_set_y(ui_Green2, -20);
    lv_obj_set_align(ui_Green2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Green2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Green2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Green2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Yellou2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Yellou2, &ui_img_firefighter_yell_full_png);
    lv_obj_set_width(ui_Yellou2, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_Yellou2, LV_SIZE_CONTENT);    /// 263
    lv_obj_set_x(ui_Yellou2, 0);
    lv_obj_set_y(ui_Yellou2, -20);
    lv_obj_set_align(ui_Yellou2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Yellou2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Yellou2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Yellou2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Red2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Red2, &ui_img_firefighter_red_full_png);
    lv_obj_set_width(ui_Red2, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Red2, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_x(ui_Red2, 0);
    lv_obj_set_y(ui_Red2, -20);
    lv_obj_set_align(ui_Red2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Red2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Red2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Red2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp2Back = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Temp2Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp2Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp2Back, 14);
    lv_obj_set_y(ui_Temp2Back, 160);
    lv_obj_set_align(ui_Temp2Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp2Back, "000");
    lv_obj_set_style_text_color(ui_Temp2Back, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp2Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp2Back, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp2Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp2, 22);
    lv_obj_set_y(ui_Temp2, 161);
    lv_obj_set_align(ui_Temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp2, "789");
    lv_obj_set_style_text_font(ui_Temp2, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HELP2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_HELP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HELP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HELP2, -5);
    lv_obj_set_y(ui_HELP2, 153);
    lv_obj_set_align(ui_HELP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HELP2, "HELP");
   // lv_obj_add_flag(ui_HELP2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_HELP2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HELP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HELP2, &ui_font_FontHelp50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HELP2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 180);
    lv_obj_set_height(ui_Container3, 390);
    lv_obj_set_x(ui_Container3, 95);
    lv_obj_set_y(ui_Container3, 25);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp3Back = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Temp3Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp3Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp3Back, 14);
    lv_obj_set_y(ui_Temp3Back, 160);
    lv_obj_set_align(ui_Temp3Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp3Back, "000");
    lv_obj_set_style_text_color(ui_Temp3Back, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp3Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp3Back, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp3Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTemp3 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_ImgTemp3, &ui_img_temperature_30_png);
    lv_obj_set_width(ui_ImgTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgTemp3, -58);
    lv_obj_set_y(ui_ImgTemp3, 158);
    lv_obj_set_align(ui_ImgTemp3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTemp3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTemp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImgTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Red3 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Red3, &ui_img_firefighter_red_full_png);
    lv_obj_set_width(ui_Red3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Red3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Red3, 0);
    lv_obj_set_y(ui_Red3, -20);
    lv_obj_set_align(ui_Red3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Red3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Red3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Red3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gray3 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Gray3, &ui_img_firefighter_gray_full_png);
    lv_obj_set_width(ui_Gray3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gray3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gray3, 0);
    lv_obj_set_y(ui_Gray3, -20);
    lv_obj_set_align(ui_Gray3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gray3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gray3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Gray3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Yellou3 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Yellou3, &ui_img_firefighter_yell_full_png);
    lv_obj_set_width(ui_Yellou3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Yellou3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Yellou3, 0);
    lv_obj_set_y(ui_Yellou3, -20);
    lv_obj_set_align(ui_Yellou3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Yellou3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Yellou3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Yellou3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Temp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp3, 22);
    lv_obj_set_y(ui_Temp3, 160);
    lv_obj_set_align(ui_Temp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp3, "789");
    lv_obj_set_style_text_font(ui_Temp3, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HELP3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_HELP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HELP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HELP3, -5);
    lv_obj_set_y(ui_HELP3, 153);
    lv_obj_set_align(ui_HELP3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HELP3, "HELP");
    //lv_obj_add_flag(ui_HELP3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_HELP3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HELP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HELP3, &ui_font_FontHelp50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HELP3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green3 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Green3, &ui_img_firefighter_green_full_png);
    lv_obj_set_width(ui_Green3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Green3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Green3, 0);
    lv_obj_set_y(ui_Green3, -20);
    lv_obj_set_align(ui_Green3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Green3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Green3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Green3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 180);
    lv_obj_set_height(ui_Container4, 390);
    lv_obj_set_x(ui_Container4, 290);
    lv_obj_set_y(ui_Container4, 25);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Red4 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Red4, &ui_img_firefighter_red_full_png);
    lv_obj_set_width(ui_Red4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Red4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Red4, 0);
    lv_obj_set_y(ui_Red4, -20);
    lv_obj_set_align(ui_Red4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Red4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Red4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Red4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green4 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Green4, &ui_img_firefighter_green_full_png);
    lv_obj_set_width(ui_Green4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Green4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Green4, 0);
    lv_obj_set_y(ui_Green4, -20);
    lv_obj_set_align(ui_Green4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Green4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Green4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Green4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gray4 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Gray4, &ui_img_firefighter_gray_full_png);
    lv_obj_set_width(ui_Gray4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gray4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gray4, 0);
    lv_obj_set_y(ui_Gray4, -20);
    lv_obj_set_align(ui_Gray4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gray4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gray4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Gray4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Yellou4 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Yellou4, &ui_img_firefighter_yell_full_png);
    lv_obj_set_width(ui_Yellou4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Yellou4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Yellou4, 0);
    lv_obj_set_y(ui_Yellou4, -20);
    lv_obj_set_align(ui_Yellou4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Yellou4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Yellou4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Yellou4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTemp4 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_ImgTemp4, &ui_img_temperature_30_png);
    lv_obj_set_width(ui_ImgTemp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgTemp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgTemp4, -62);
    lv_obj_set_y(ui_ImgTemp4, 157);
    lv_obj_set_align(ui_ImgTemp4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTemp4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTemp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImgTemp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp4Back = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Temp4Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp4Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp4Back, 14);
    lv_obj_set_y(ui_Temp4Back, 160);
    lv_obj_set_align(ui_Temp4Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp4Back, "000");
    lv_obj_set_style_text_color(ui_Temp4Back, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp4Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp4Back, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp4Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Temp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp4, 22);
    lv_obj_set_y(ui_Temp4, 160);
    lv_obj_set_align(ui_Temp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp4, "789");
    lv_obj_set_style_text_font(ui_Temp4, &ui_font_Font60segment, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HELP4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_HELP4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HELP4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HELP4, -5);
    lv_obj_set_y(ui_HELP4, 153);
    lv_obj_set_align(ui_HELP4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HELP4, "HELP");
   // lv_obj_add_flag(ui_HELP4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_HELP4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HELP4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HELP4, &ui_font_FontHelp50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HELP4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Titulo_Touch_Fire = NULL;
    ui_Container1 = NULL;
    ui_Gray1 = NULL;
    ui_Red1 = NULL;
    ui_Yellou1 = NULL;
    ui_Green1 = NULL;
    ui_HELP1 = NULL;
    ui_ImgTemp1 = NULL;
    ui_Temp1Back = NULL;
    ui_Temp1 = NULL;
    ui_Container2 = NULL;
    ui_Gray2 = NULL;
    ui_ImgTemp2 = NULL;
    ui_Green2 = NULL;
    ui_Yellou2 = NULL;
    ui_Red2 = NULL;
    ui_Temp2Back = NULL;
    ui_Temp2 = NULL;
    ui_HELP2 = NULL;
    ui_Container3 = NULL;
    ui_Temp3Back = NULL;
    ui_ImgTemp3 = NULL;
    ui_Red3 = NULL;
    ui_Gray3 = NULL;
    ui_Yellou3 = NULL;
    ui_Temp3 = NULL;
    ui_HELP3 = NULL;
    ui_Green3 = NULL;
    ui_Container4 = NULL;
    ui_Red4 = NULL;
    ui_Green4 = NULL;
    ui_Gray4 = NULL;
    ui_Yellou4 = NULL;
    ui_ImgTemp4 = NULL;
    ui_Temp4Back = NULL;
    ui_Temp4 = NULL;
    ui_HELP4 = NULL;

}
