// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: APS_Base_4M

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Titulo_Touch_Fire;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Gray1;
extern lv_obj_t * ui_Red1;
extern lv_obj_t * ui_Yellou1;
extern lv_obj_t * ui_Green1;
extern lv_obj_t * ui_HELP1;
extern lv_obj_t * ui_ImgTemp1;
extern lv_obj_t * ui_Temp1Back;
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Gray2;
extern lv_obj_t * ui_ImgTemp2;
extern lv_obj_t * ui_Green2;
extern lv_obj_t * ui_Yellou2;
extern lv_obj_t * ui_Red2;
extern lv_obj_t * ui_Temp2Back;
extern lv_obj_t * ui_Temp2;
extern lv_obj_t * ui_HELP2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Temp3Back;
extern lv_obj_t * ui_ImgTemp3;
extern lv_obj_t * ui_Red3;
extern lv_obj_t * ui_Gray3;
extern lv_obj_t * ui_Yellou3;
extern lv_obj_t * ui_Temp3;
extern lv_obj_t * ui_HELP3;
extern lv_obj_t * ui_Green3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Red4;
extern lv_obj_t * ui_Green4;
extern lv_obj_t * ui_Gray4;
extern lv_obj_t * ui_Yellou4;
extern lv_obj_t * ui_ImgTemp4;
extern lv_obj_t * ui_Temp4Back;
extern lv_obj_t * ui_Temp4;
extern lv_obj_t * ui_HELP4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

